import { describe, expect, it } from "vitest";
import { canonicalizeJson, computePayloadHash, isValidSha256Hex, sha256Hex } from "../src/canonicalize";
import type { TracepackEvidencePayloadV1 } from "../src/types";

// The exact bytes fetched from github.com/cyberphone/json-canonicalization
// (testdata/input/*.json, testdata/output/*.json) — the RFC 8785 authors' own reference
// implementation's published input/expected-canonical-output pairs, not retyped by hand.
// `?raw` imports the file's literal text content, so nothing about escape sequences,
// non-ASCII characters, or exact whitespace is at risk of being mistranscribed the way a
// hand-typed fixture would be (an earlier attempt at this file did exactly that, hand-typing
// these strings, and got the syntax broken and the content wrong on the first try).
import valuesInput from "./fixtures/rfc8785/values.input.json?raw";
import valuesOutput from "./fixtures/rfc8785/values.output.txt?raw";
import arraysInput from "./fixtures/rfc8785/arrays.input.json?raw";
import arraysOutput from "./fixtures/rfc8785/arrays.output.txt?raw";
import frenchInput from "./fixtures/rfc8785/french.input.json?raw";
import frenchOutput from "./fixtures/rfc8785/french.output.txt?raw";
import structuresInput from "./fixtures/rfc8785/structures.input.json?raw";
import structuresOutput from "./fixtures/rfc8785/structures.output.txt?raw";
import weirdInput from "./fixtures/rfc8785/weird.input.json?raw";
import weirdOutput from "./fixtures/rfc8785/weird.output.txt?raw";

describe("canonicalizeJson", () => {
  it("sorts object keys recursively regardless of input order", () => {
    const a = canonicalizeJson({ b: 1, a: { d: 2, c: 3 } });
    const b = canonicalizeJson({ a: { c: 3, d: 2 }, b: 1 });
    expect(a).toBe(b);
    expect(a).toBe('{"a":{"c":3,"d":2},"b":1}');
  });

  it("preserves array order — order is semantically meaningful for observations", () => {
    expect(canonicalizeJson({ list: [3, 1, 2] })).toBe('{"list":[3,1,2]}');
  });

  // The RFC 8785 authors publish their own input/expected-output pairs at
  // github.com/cyberphone/json-canonicalization/tree/master/testdata, generated by their own
  // reference implementation — independent of the `canonicalize` npm package this file wraps
  // and independent of anything in this repository. Comparing our actual shipped
  // canonicalizeJson() against the standard's own authoritative examples, byte for byte, is a
  // stronger cross-check than comparing against one other library: a second library could
  // coincidentally share the same bug, but the standard's own worked examples can't be wrong
  // by definition. Each pair was fetched and verified against `canonicalize@3.0.0` directly
  // (not just read) before being copied into tests/fixtures/rfc8785/ verbatim.
  describe("against RFC 8785's own official test vectors (not re-derived from this package)", () => {
    it("values.json — numbers, escapes, and Unicode", () => {
      expect(canonicalizeJson(JSON.parse(valuesInput))).toBe(valuesOutput);
    });

    it("arrays.json", () => {
      expect(canonicalizeJson(JSON.parse(arraysInput))).toBe(arraysOutput);
    });

    it("french.json — accented keys", () => {
      expect(canonicalizeJson(JSON.parse(frenchInput))).toBe(frenchOutput);
    });

    it("structures.json — nested objects, numeric-looking keys, empty objects", () => {
      expect(canonicalizeJson(JSON.parse(structuresInput))).toBe(structuresOutput);
    });

    it("weird.json — property names that look like escape sequences or numbers", () => {
      expect(canonicalizeJson(JSON.parse(weirdInput))).toBe(weirdOutput);
    });
  });
});

describe("sha256Hex", () => {
  it("matches a known test vector for an empty string", async () => {
    expect(await sha256Hex("")).toBe("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855");
  });

  it("produces a hash isValidSha256Hex accepts", async () => {
    expect(isValidSha256Hex(await sha256Hex("hello"))).toBe(true);
  });

  // SPEC.md section 6.1's worked test vector: SHA-256 of a known 38-byte UTF-8 string,
  // computed independently (Node's crypto module, outside this codebase) before being pinned
  // here. Any implementation following section 6.1's procedure — hash the original binary
  // bytes, never the base64 text — must reproduce this exact value.
  it("matches SPEC.md section 6.1's attachment content_hash test vector", async () => {
    const bytes = new TextEncoder().encode("Tracepack interchange test attachment.");
    expect(bytes.length).toBe(38);
    expect(await sha256Hex(bytes)).toBe("a07b37177fb90cbf3a9c37f003425ad458e71f209c87b2c8f0b3512dc90c2694");
  });
});

describe("isValidSha256Hex", () => {
  it("rejects anything that isn't exactly 64 lowercase hex characters", () => {
    expect(isValidSha256Hex("a".repeat(64))).toBe(true);
    expect(isValidSha256Hex("A".repeat(64))).toBe(false);
    expect(isValidSha256Hex("a".repeat(63))).toBe(false);
    expect(isValidSha256Hex("g".repeat(64))).toBe(false);
    expect(isValidSha256Hex(123)).toBe(false);
  });
});

describe("computePayloadHash", () => {
  const base: TracepackEvidencePayloadV1 = {
    schema_version: 1,
    source: { producer_id: "com.example.tool", producer_name: "Example Tool" },
    capture_timestamp: "2026-01-01T00:00:00Z",
    evidence_type: "test",
    attachments: [{ id: "a1", filename: "f.png", mime_type: "image/png", size: 3, content_hash: "a".repeat(64), encoding: "base64", data: "AAAA" }],
    observations: [],
    integrity: { algorithm: "sha256", canonicalization: "RFC8785", payload_hash: "b".repeat(64) },
  };

  it("does not change when only attachments[].data changes", async () => {
    const hashA = await computePayloadHash(base);
    const hashB = await computePayloadHash({ ...base, attachments: [{ ...base.attachments[0]!, data: "ZZZZ" }] });
    expect(hashA).toBe(hashB);
  });

  it("does not change when only integrity.payload_hash changes", async () => {
    const hashA = await computePayloadHash(base);
    const hashB = await computePayloadHash({ ...base, integrity: { ...base.integrity, payload_hash: "c".repeat(64) } });
    expect(hashA).toBe(hashB);
  });

  it("changes when semantic content changes", async () => {
    const hashA = await computePayloadHash(base);
    const hashB = await computePayloadHash({ ...base, evidence_type: "different" });
    expect(hashA).not.toBe(hashB);
  });

  it("is order-independent for how the object literal was constructed (two producers, identical evidence, identical hash)", async () => {
    const reordered: TracepackEvidencePayloadV1 = {
      observations: [],
      evidence_type: "test",
      schema_version: 1,
      attachments: base.attachments,
      capture_timestamp: "2026-01-01T00:00:00Z",
      source: { producer_name: "Example Tool", producer_id: "com.example.tool" },
      integrity: base.integrity,
    };
    expect(await computePayloadHash(reordered)).toBe(await computePayloadHash(base));
  });

  // SPEC.md section 6.2's full worked test vector — a complete minimal payload, its exact
  // canonical form, and the resulting payload_hash. Independently recomputed (Node's crypto
  // module plus the `canonicalize` npm package directly, outside this codebase) and
  // cross-checked against this package's own computePayloadHash before being pinned here —
  // both must agree, since they're supposed to implement the same algorithm.
  it("matches SPEC.md section 6.2's full payload test vector", async () => {
    const payload: TracepackEvidencePayloadV1 = {
      schema_version: 1,
      source: { producer_id: "com.example.minimal-producer", producer_name: "Minimal Test Producer" },
      capture_timestamp: "2026-01-01T00:00:00Z",
      evidence_type: "test_fixture",
      attachments: [{
        id: "a1", filename: "test.txt", mime_type: "application/pdf", size: 38,
        content_hash: "a07b37177fb90cbf3a9c37f003425ad458e71f209c87b2c8f0b3512dc90c2694",
        encoding: "base64", data: "VHJhY2VwYWNrIGludGVyY2hhbmdlIHRlc3QgYXR0YWNobWVudC4=",
      }],
      observations: [],
      integrity: { algorithm: "sha256", canonicalization: "RFC8785", payload_hash: "0".repeat(64) },
    };
    expect(await computePayloadHash(payload)).toBe("916f46f76f4f07438fcca91f9c3371cf02ed3cca66f9e8062c24bf415f4a8573");
  });
});
