// Cross-checks fixture-payload.json (generated by Support/test-payload-builder.php from a fake
// conversation) against the real @tracepack/evidence-sdk validator and its own RFC 8785 hash
// implementation. Proves the PHP payload builder's output is schema-valid and byte-for-byte
// hash-compatible with the TypeScript side of the interchange contract, not just eyeballed.
//
// Run from this directory after regenerating the fixture:
//   php ../Modules/TracepackForFreescout/Support/test-payload-builder.php
//   node verify-payload.mjs
//
// Requires @tracepack/evidence-sdk to already be built (pnpm install's postinstall does this
// for the whole monorepo; run `pnpm --filter @tracepack/evidence-sdk build` directly if not).
import { validateEvidencePayload, computePayloadHash } from "../../../packages/evidence-sdk/dist/index.js";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const dir = path.dirname(fileURLToPath(import.meta.url));
const payload = JSON.parse(fs.readFileSync(path.join(dir, "fixture-payload.json"), "utf8"));

const result = validateEvidencePayload(payload);
if (!result.ok) {
  console.error("Schema validation FAILED:", JSON.stringify(result.issues, null, 2));
  process.exit(1);
}
console.log("Schema validation: ok");

const recomputed = await computePayloadHash(payload);
if (recomputed !== payload.integrity.payload_hash) {
  console.error(`Hash mismatch. PHP computed ${payload.integrity.payload_hash}, TS recomputed ${recomputed}`);
  process.exit(1);
}
console.log("payload_hash matches the TypeScript RFC 8785 implementation:", recomputed);
console.log("ALL CHECKS PASSED");
