import { StrictMode, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

function Mark() { return <svg className="mark" viewBox="0 0 96 96" aria-hidden="true"><rect x="24" y="18" width="52" height="64" rx="10" transform="rotate(-6 50 50)"/><rect x="24" y="18" width="52" height="64" rx="10" transform="rotate(6 50 50)"/><circle className="hole" cx="50" cy="44" r="9"/><rect className="hole" x="46" y="50" width="8" height="18" rx="3"/></svg> }

const demos = {
  cli: ["$ npm install -g @tracepack/cli", "$ tracepack validate-evidence record.json", "✓ Valid tracepack-evidence v1 payload", "  Example Tool · 2 attachments · 1 observation", "i Producer identity is self asserted"],
  sdk: ["$ npm install @tracepack/evidence-sdk", "import { validateEvidencePayload } from '@tracepack/evidence-sdk';", "const result = validateEvidencePayload(payload);", "✓ result.success  true", "i Ready to send to TracePack"],
  compare: ["$ tracepack diff-manifest before.json after.json", "  Added      photo-12", "  Changed    agreement-04", "  Removed    none", "✓ Compared by evidence id and content hash"],
} as const;
type Demo = keyof typeof demos;

function App() {
  const [demo, setDemo] = useState<Demo>("cli");
  return <>
    <header><a className="brand" href="#top"><Mark/>TracePack <span>Developers</span></a><nav><a href="#start">Get started</a><a href="#format">Evidence format</a><a href="#integrate">Integrate</a><a href="https://github.com/ace2016/tracepack">GitHub</a></nav><a className="open" href="https://app.tracepack.org">Open TracePack</a></header>
    <main id="top">
      <section className="hero"><div><p className="eyebrow">Build with TracePack</p><h1>Create evidence that remains understandable.</h1><p className="lead">Validate templates and evidence, produce portable records, compare exported manifests and send evidence into a local TracePack workspace.</p><div className="actions"><a className="button" href="#start">Get started</a><a className="button quiet" href="https://github.com/ace2016/tracepack">View the source</a></div><p className="licence">Open source. Built around a portable evidence contract.</p></div>
        <div className="demo"><div className="tabs">{(Object.keys(demos) as Demo[]).map(key=><button className={demo===key?"active":""} onClick={()=>setDemo(key)} key={key}>{key === "compare" ? "Compare" : key.toUpperCase()}</button>)}</div><div className="terminal" key={demo}><div className="terminalTop"><i/><i/><i/><span>tracepack</span></div><div className="lines">{demos[demo].map((line,i)=><code className={line.startsWith("✓")?"good":line.startsWith("i")?"notice":""} style={{animationDelay:`${i*.42}s`}} key={line}>{line}</code>)}</div></div></div>
      </section>
      <section className="capabilities"><article><b>Validate</b><p>Check templates and evidence payloads against the real TracePack contracts.</p></article><article><b>Produce</b><p>Create portable evidence from another product without hiding its origin.</p></article><article><b>Compare</b><p>See what changed between exported manifests using stable identifiers and hashes.</p></article><article><b>Import</b><p>Hand evidence to the local workspace through a deliberate review screen.</p></article></section>
      <section className="section" id="start"><div className="heading"><p className="eyebrow">Start with the tool you need</p><h2>One contract, several ways to use it.</h2></div><div className="cards"><article><span>01</span><h3>Command line</h3><pre>npm install -g @tracepack/cli</pre><p>Validate a template, check an evidence payload or compare two manifests.</p><a href="https://github.com/ace2016/tracepack/blob/main/packages/cli/README.md">Explore the CLI →</a></article><article><span>02</span><h3>TypeScript SDK</h3><pre>npm install @tracepack/evidence-sdk</pre><p>Use the frozen v1 types, validator, canonicalisation and hashing helpers.</p><a href="https://github.com/ace2016/tracepack/blob/main/packages/evidence-sdk/README.md">Explore the SDK →</a></article><article><span>03</span><h3>Build without the SDK</h3><pre>tracepack-evidence v1</pre><p>Implement the open JSON contract in any language using the schema and test vectors.</p><a href="#format">Read the format →</a></article></div></section>
      <section className="dark" id="format"><div><p className="eyebrow">A deliberate trust boundary</p><h2>Integrity is not the same as truth.</h2><p>TracePack can verify that bytes and structured payloads have not changed. An external observation remains attributed to the producer that reported it. Human judgement decides what it means and whether it should be relied upon.</p></div><div className="trust"><div><span>01</span><b>Attachment bytes</b><small>SHA 256 content hash</small></div><div><span>02</span><b>Evidence payload</b><small>RFC 8785 canonical form</small></div><div><span>03</span><b>Producer claim</b><small>Clearly attributed</small></div><div className="human"><span>04</span><b>Human decision</b><small>Never silently automated</small></div></div></section>
      <section className="section integrate" id="integrate"><div><p className="eyebrow">Send to TracePack</p><h2>Let people carry evidence out of your product.</h2><p className="lead">Open the TracePack import destination, wait until the workspace is ready, then send a valid evidence payload. The person reviews it before choosing where it belongs.</p><a className="button" href="https://app.tracepack.org/import">Open the import destination</a></div><pre><span>your product</span>{`\n       ↓\n`}<b>tracepack-evidence v1</b>{`\n       ↓\n`}<span>import review</span>{`\n       ↓\n`}<strong>local evidence pack</strong></pre></section>
    </main>
    <footer><a className="brand" href="#top"><Mark/>TracePack</a><p>Portable evidence with visible provenance.</p><div><a href="https://tracepack.org">Product</a><a href="https://docs.tracepack.org">Documentation</a><a href="https://github.com/ace2016/tracepack">GitHub</a></div></footer>
  </>;
}
createRoot(document.getElementById("root")!).render(<StrictMode><App/></StrictMode>);
